services:
  svelte:
    container_name: svelte
    restart: always
    ports:
      - 5173-5173
    depends_on:
      db:
        condition: service_started
        required: false
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - clinic_system
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coffeelake
      MYSQL_DATABASE: pos
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
    networks:
      - clinic_system
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - clinic_system
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: always
    networks:
      - clinic_system
    ports:
      - 80:80
      - 443:443
      - 8000:8000

    volumes:
      - ./Caddyfile-dev:/etc/caddy/Caddyfile
      - ./static/uploads:/uploads

networks:
  clinic_system:
    driver: bridge
